### PR TITLE
Update API from gitea.com

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Comment by slonopotamus** [comment]
@zeripath You [still](https://github.com/zeripath/java-gitea-api/pull/1#issuecomment-542086049) don't have CI enabled for PRs, so see test run in my fork: https://travis-ci.com/github/slonopotamus/java-gitea-api/builds/219365074

**Comment by slonopotamus** [comment]
Also, could you please roll out a new release after merging this? I would like to use some new API in git-as-svn and current java-gitea-api is too old. It would be cool if jars were still built using Java 8, though Java 11 would be OK too.

**Comment by zeripath** [comment]
Heya sorry I've left this to rot somewhat. I'll leave a tab open and get things sorted tomorrow.

Thanks @slonopotamus

**Comment by zeripath** [comment]
Hopefully I've pushed things up correctly now - there should be a 1.14.0-SNAPSHOT up for you to use.

**Pull request merged**
